version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    networks:
      - treinamento
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    env_file:
      - .env
    networks:
      - treinamento
    ports:
      - "5672:5672"
      - "15672:15672"

  react-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - treinamento
    ports:
      - "5001:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - treinamento
    env_file:
      - ./api/.env
    depends_on:
      - rabbitmq

networks:
  treinamento:
    driver: bridge
